import { Shop, Merchant, AdminUser, Offer, Claim } from '../types';

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: 'admin-suraj',
    email: 'surajadmin@gmail.com',
    passwordHash: 'surajadmin@#',
    name: 'Suraj Admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'admin-1',
    email: 'admin@scratchease.com',
    passwordHash: 'admin123',
    name: 'Master Admin',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 'shop-brew',
    name: 'Brew & Bean Cafe',
    slug: 'brew-and-bean',
    category: 'Cafe & Bakery',
    address: 'Block C, Inner Circle, Connaught Place, New Delhi',
    phone: '+91 98101 23456',
    latitude: 28.6315,
    longitude: 77.2167,
    radiusMeters: 75,
    wifiIp: '192.168.1.1',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'shop-urban',
    name: 'Urban Trend Fashion',
    slug: 'urban-trend',
    category: 'Apparel & Lifestyle',
    address: 'DLF CyberHub, Sector 24, Gurugram',
    phone: '+91 98102 34567',
    latitude: 28.4952,
    longitude: 77.0894,
    radiusMeters: 75,
    wifiIp: '192.168.2.1',
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'shop-pizza',
    name: 'Gourmet Pizza Hub',
    slug: 'gourmet-pizza',
    category: 'Italian & Dine-in',
    address: '100ft Road, Indiranagar, Bengaluru',
    phone: '+91 98103 45678',
    latitude: 12.9784,
    longitude: 77.6408,
    radiusMeters: 75,
    wifiIp: '192.168.3.1',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'merchant-brew',
    shopId: 'shop-brew',
    email: 'brew@shop.com',
    passwordHash: 'shop123',
    name: 'Vikram Mehta (Store Manager)',
    phone: '+91 98101 23456',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'merchant-urban',
    shopId: 'shop-urban',
    email: 'urban@shop.com',
    passwordHash: 'shop123',
    name: 'Ananya Sen (Store Manager)',
    phone: '+91 98102 34567',
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'merchant-pizza',
    shopId: 'shop-pizza',
    email: 'pizza@shop.com',
    passwordHash: 'shop123',
    name: 'Rohan Iyer (Store Manager)',
    phone: '+91 98103 45678',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'offer-10-percent',
    title: 'Flat 10% OFF Bill Discount',
    discountPercent: 10,
    description: 'Instant 10% deduction on your in-store dining or shopping bill.',
    terms: 'Valid once per customer per day. Present to the cashier prior to billing.',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_CLAIMS: Claim[] = [
  {
    id: 'claim-demo-1',
    claimCode: 'SCR-4819',
    customerId: 'cust-1',
    customerName: 'Rahul Sharma',
    customerMobile: '9876543210',
    shopId: 'shop-brew',
    shopName: 'Brew & Bean Cafe',
    offerId: 'offer-10-percent',
    offerTitle: 'Flat 10% OFF Bill Discount',
    discountPercent: 10,
    status: 'ACCEPTED',
    scratchRevealed: true,
    identificationMethod: 'GEOFENCE',
    customerLat: 28.6314,
    customerLng: 77.2166,
    distanceMeters: 14,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 43 * 60000).toISOString(),
    resolvedBy: 'Vikram Mehta',
  },
  {
    id: 'claim-demo-2',
    claimCode: 'SCR-5920',
    customerId: 'cust-2',
    customerName: 'Pooja Verma',
    customerMobile: '9811223344',
    shopId: 'shop-urban',
    shopName: 'Urban Trend Fashion',
    offerId: 'offer-10-percent',
    offerTitle: 'Flat 10% OFF Bill Discount',
    discountPercent: 10,
    status: 'ACCEPTED',
    scratchRevealed: true,
    identificationMethod: 'GEOFENCE',
    customerLat: 28.4953,
    customerLng: 77.0895,
    distanceMeters: 18,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 118 * 60000).toISOString(),
    resolvedBy: 'Ananya Sen',
  },
];
